name: python CI
on:
  push:
    branches:
      -main
  pull_request:
    branches:
      -main
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    #step 1:checking out the code from action/checkout@v2
      - name: check out the code
        uses: actions/checkout@v2
    #step 2: set up the python environment
      - name: setup env
        uses: actions/setup-python@v2
        with:
          python-version:'3.8' 
    #step 3: install dependencies
      - name: install depedencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    #step 4:run tests
      - name: run tests
        run:  pytest
